[package]
name = "BeerHolderBot"
version = "0.1.0"
authors = ["Eric S. Londres <elondres@stevens.edu>"]
edition = "2018"

[dependencies]
teloxide = "0.3"
teloxide-macros = "0.3"
log = "0.4.8"
pretty_env_logger = "0.4.0"
tokio = { version =  "0.2.11", features = ["rt-threaded", "macros"] }